spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/art_shop?createDatabaseIfNotExist=true
    username: root
    password: rootpassword
  jpa:
    show-sql: true